def acc_gdd(cdsLogin, startDate, endDate, area, Tbase, output):

    # Create the output directory
    os.makedirs(output, exist_ok=False)    

    # Credentials to CDS datasets
    cds_login = cdsLogin
    
    start_date = datetime.strptime(startDate, '%d/%m/%Y')   # Start of analysis period 
    end_date = datetime.strptime(endDate, '%d/%m/%Y')       # End of analysis period 
    
    # Generate a list of months and days based on the start and end dates
    years_range = [str(i).zfill(2) for i in range(start_date.year, end_date.year + 1)]
    #year = str(start_date.year) 
    months_range = [str((i % 12) + 1).zfill(2) for i in range(start_date.month - 1, start_date.month - 1 + (end_date.year - start_date.year) * 12 + end_date.month - start_date.month + 1)]
    days_range = [str(i).zfill(2) for i in range(1, 32)]
    
    
    # Extract extent of area of interest
    extent = area.total_bounds
    # Extract maxmimum extent of AOI - coordinates N, W, S and E
    N, W, S, E = extent[3], extent[0], extent[1], extent[2]
    
    # Download data grtom CDS - base querry is generated by CDS API but could be modificated (like this one)
    cds_login.retrieve(
        'sis-agrometeorological-indicators',                            # Dataset
        {
            'format': 'zip',                                            # Format
            'variable': '2m_temperature',                               # Variable
            'year': years_range,                                        # List of years
            'month': months_range,                                      # List of months
            'statistic': ['24_hour_mean'],                           # Statistics of variable
            'day': days_range,                                          # List of days
            'area': [N, W, S, E],                                       # Extent of AOI
            'version': '1_1',                                           # Specify the version
            },
        f'{output}/download_max.zip')                                   # Path directory with name of new created file (+extension)
    
    # Path to donloaded .zip file
    downloaded_file = f'{output}/download_max.zip'
    
cdsLogin = cdsapi.Client()
startDate = '01/01/2022'
endDate = '31/12/2022'
area = gpd.read_file('/dane_statyczne/Panstwo.shp')
Tbase = 10
output = f'agrotech/test/gdd_2022_tb{Tbase}'  # The folder where you want to extract the data

    
